language: java
install: true

env:
  global:
  - DISTRO_PATH=./target/dotto-distro-$(mvn -q -Dexec.executable=echo -Dexec.args='${project.version}' --non-recursive exec:exec)

script:
  - mvn clean install

cache:
  directories:
  - .autoconf
  - $HOME/.m2

jdk:
  - openjdk11

deploy:
  # Deploy binaries to OpenShift
  - provider: script
    skip_cleanup: true
    script: mvn alfresco:run -Dmaven.alfresco.startTomcat=false && mkdir -p $DISTRO_PATH && mv target/*.war $DISTRO_PATH && mv $DISTRO_PATH/platform.war $DISTRO_PATH/alfresco.war && zip -r $DISTRO_PATH.zip $DISTRO_PATH
    on:
      tags: true
  - provider: releases
    api_key: "$GH_TOKEN"
    file: "$DISTRO_PATH.zip"
    skip_cleanup: true
    on:
      tags: true