language: java
install: true

# env:
#   global:
#   -

script:
  - export DISTRO_PATH=./target/dotto-distro-$(mvn -q -Dexec.executable=echo -Dexec.args='${project.version}' --non-recursive exec:exec)
  - ./prepare-distro.sh

cache:
  directories:
  - .autoconf
  - $HOME/.m2

jdk:
  - openjdk11

deploy:
  - provider: releases
    api_key: "$GH_TOKEN"
    file_glob: true
    file: "$DISTRO_PATH/*"
    skip_cleanup: true
    on:
      tags: true